datapull:
  application:
    region: us-east-1
  secretstore:
    vault:
      vault_url: https://vault-us-east-1.egdp-stage.aws.away.black:8200
      static_secret_path_prefix: /v1/dbops/staticsecrets/awsenvironments/awsregions/us-east-1/clusters/v1/auth/aws-ec2/login
      vault_nonce: f2d47637-4b41-fdad-f556-b657ff2c0edb
      vault_path_login:
  json:
    inputjson: Input_Sample_filesystem-to-filesystem.json
  spark:
    network: spark.network.timeout
    timeout: 10000s
    executor: spark.executor.heartbeatInterval
    interval: 1000s
    broadcasttimeout: spark.sql.broadcastTimeout
    btimeout: 36000
    scheduler: spark.scheduler.mode
    mode: FAIR
    failures: spark.task.maxFailures
  miscellaneous:
    no_of_retries: 16
    timeout: 10000
    consul_url:
    sleeptimeout: 60000
  api:
    s3_bucket_name: egdp-stage-data-datatools-us-east-1
    application_subnet_1: subnet-0131cffab62cc0419
    application_subnet_2: subnet-08b0ce8e6b49636c5
    application_security_group: sg-0c05bb838ca2f94ff
    vpc_id: vpc-0087f4c1ce9648e0e
    load_balancer_certificate_arn: arn:aws:acm:us-east-1:044815873833:certificate/c309ae69-a238-4471-a85c-a5208b259eff
  emr:
    emr_security_group_master: sg-0521706319ed535c6
    emr_security_group_slave: sg-093c108ef9515882e
    emr_security_group_service_access: sg-0130f461bccacef6e
    tags:
      Brand: HomeAway
      Owner: HA_DataTools@expediacorp.onmicrosoft.com
      Purpose: EMRPipeline
      Service: emr
      Platform: EMRPipeline
      ComponentInfo: 7f99fe6f-4675-4ef2-b88f-a48cf92bc00a
      AssetProtectionLevel: 99
      Portfolio: Data Engineering Services
      Creator: HA_DataTools@expediacorp.onmicrosoft.com
      Team: DataTools
      Env: egdp-stage
      Name: ECS_datapull_stage
  logger:
    cloudwatch:
      groupName: /ecs/datatools-datapull-api
      streamName: datapull-stream
    mssql:
      server:
      database:
      login:
      password:
      table:
      driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  email:
    smtp:
      emailaddress: HA_DataTools@expediacorp.onmicrosoft.com
      smtpserveraddress: mailq-stage-egdp.expedia.biz
    ses:
      region:
      email:
      access_key:
      secret_key:
