datapull:
  application:
    region: us-east-1
  secretstore:
    vault:
      vault_url: https://vault-us-east-1.egdp-test.aws.away.black:8200
      static_secret_path_prefix: /v1/dbops/staticsecrets/awsenvironments/awsregions/us-east-1/clusters/v1/auth/aws-ec2/login
      vault_nonce: f2d47637-4b41-fdad-f556-b657ff2c0edb
      vault_path_login:
  json:
    inputjson: Input_Sample_filesystem-to-filesystem.json
  spark:
    network: spark.network.timeout
    timeout: 10000s
    executor: spark.executor.heartbeatInterval
    interval: 1000s
    broadcasttimeout: spark.sql.broadcastTimeout
    btimeout: 36000
    scheduler: spark.scheduler.mode
    mode: FAIR
    failures: spark.task.maxFailures
  miscellaneous:
    no_of_retries: 16
    timeout: 10000
    consul_url:
    sleeptimeout: 60000
  api:
    s3_bucket_name: egdp-test-data-datatools-us-east-1
    application_subnet_1: subnet-02649333aa3e397bb
    application_subnet_2: subnet-028ea9529c728d7b9
    application_security_group: sg-038c5b844af024e31
    vpc_id: vpc-0618333437f727d62
    load_balancer_certificate_arn:
  emr:
    emr_security_group_master: sg-042a7ff660c5d9d47
    emr_security_group_slave: sg-03d6331f153cc1d0d
    emr_security_group_service_access: sg-04317ff46f72b901e
    tags:
      Brand: HomeAway
      Owner: HA_DataTools@expediacorp.onmicrosoft.com
      Purpose: EMRPipeline
      Service: emr
      Platform: EMRPipeline
      ComponentInfo: 7f99fe6f-4675-4ef2-b88f-a48cf92bc00a
      AssetProtectionLevel: 99
      Portfolio: Data Engineering Services
      Creator: HA_DataTools@expediacorp.onmicrosoft.com
      Team: DataTools
      Env: egdp-test
      Name: ECS_datapull_test
  logger:
    cloudwatch:
      groupName: /ecs/datatools-datapull-api
      streamName: datapull-stream
    mssql:
      server:
      database:
      login:
      password:
      table:
      driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  email:
    smtp:
      emailaddress: HA_DataTools@expediacorp.onmicrosoft.com
      smtpserveraddress: mailq-test-egdp.expedia.biz
    ses:
      region:
      email:
      access_key:
      secret_key:
