datapull:
  api:
    s3_bucket_name:
    application_subnet_1:
    application_subnet_2:
    application_security_group:
    vpc_id:
    load_balancer_certificate_arn:
  emr:
    emr_security_group_master:
    emr_security_group_slave:
    emr_security_group_service_access:
    hive_properties:
      hive_metastore_uris:
      hive_security_authorization_createtable_role_grants:
      hive_metastore_client_socket_timeout:
    tags:
      Brand:
      Category:
      Owner:
      Purpose:
      Service:
      Platform:
  application:
    region:
  logger:
    s3:
      loggingfolder:
    cloudwatch:
      groupName:
      streamName:
      region:

