datapull:
  api:
    s3_bucket_name:
  secretstore:
    vault:
      vault_url:
      static_secret_path_prefix:
      vault_nonce:
      vault_path_login:
  json:
    inputjson: Input_Sample_filesystem-to-Email.json
  spark:
    network:
    timeout:
    executor:
    interval:
    broadcasttimeout:
    btimeout:
    scheduler:
    mode:
    failures:
  miscellaneous:
    no_of_retries:
    timeout:
    consul_url:
    sleeptimeout:
  application:
    region:
  logger:
    s3:
      loggingfolder: /Users/nishah/desktop/dsedata
    mssql:
      server:
      database:
      login:
      password:
      table:
      driver:
    cloudwatch:
      groupName:
      streamName:
  email:
    smtp:
      emailaddress:
      smtpserveraddress:
    ses:
      email:
      access_key:
      secret_key: